server:
  domain: user
  version: 1.0
  jwtSecret: FanOne
  grpcAddress: "127.0.0.1:10001"

mysql:
  host: 127.0.0.1
  port: 3306
  database: grpc_todolist_tmp
  username: root
  password: 123456789zwm
  charset: utf8mb4

etcd:
  address: 127.0.0.1:2379

redis:
  address: 127.0.0.1:6379
  password: