basePath: /
definitions:
  advert_api.AdvertRequest:
    properties:
      href:
        type: string
      images:
        type: string
      is_show:
        type: boolean
      title:
        type: string
    required:
    - href
    - images
    - title
    type: object
  ctype.ImageType:
    enum:
    - 1
    - 2
    type: integer
    x-enum-comments:
      Local: local
      QiNiu: qiniu
    x-enum-varnames:
    - Local
    - QiNiu
  images_api.ImageResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      path:
        type: string
    type: object
  models.AdvertModel:
    properties:
      created_at:
        type: string
      href:
        type: string
      id:
        type: integer
      images:
        type: string
      is_show:
        type: boolean
      title:
        type: string
    type: object
  models.BannerModel:
    properties:
      created_at:
        type: string
      hash:
        type: string
      id:
        type: integer
      image_type:
        $ref: '#/definitions/ctype.ImageType'
      name:
        type: string
      path:
        type: string
    type: object
  models.RemoveRequest:
    properties:
      id_list:
        items:
          type: integer
        type: array
    type: object
  res.ListResponse-models_AdvertModel:
    properties:
      count:
        type: integer
      list:
        $ref: '#/definitions/models.AdvertModel'
    type: object
  res.ListResponse-models_BannerModel:
    properties:
      count:
        type: integer
      list:
        $ref: '#/definitions/models.BannerModel'
    type: object
  res.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: gvb_server API文档
  title: gvb_server API文档
  version: "1.0"
paths:
  /api/adverts:
    delete:
      description: 批量删除广告
      parameters:
      - description: 广告id列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RemoveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 批量删除广告
      tags:
      - 广告管理
    get:
      description: 广告列表
      parameters:
      - in: query
        name: key
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.ListResponse-models_AdvertModel'
              type: object
      summary: 广告列表
      tags:
      - 广告管理
    post:
      description: 创建广告
      parameters:
      - description: 表示多个参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/advert_api.AdvertRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 创建广告
      tags:
      - 广告管理
  /api/adverts/:id:
    put:
      description: 更新广告
      parameters:
      - description: 广告的一些参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/advert_api.AdvertRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 更新广告
      tags:
      - 广告管理
  /api/image_names:
    get:
      description: 图片名称列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/images_api.ImageResponse'
                  type: array
              type: object
      summary: 图片名称列表
      tags:
      - 图片管理
  /api/images:
    get:
      description: 图片列表
      parameters:
      - in: query
        name: key
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.ListResponse-models_BannerModel'
              type: object
      summary: 图片列表
      tags:
      - 图片管理
swagger: "2.0"
